# Generated by Django 4.0.5 on 2022-06-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
